// Code generated by MockGen. DO NOT EDIT.
// Source: controller.go

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/isaacRevan24/gamification-toolkit-logic/model"
)

// MockUserControllerInterface is a mock of UserControllerInterface interface.
type MockUserControllerInterface struct {
	ctrl     *gomock.Controller
	recorder *MockUserControllerInterfaceMockRecorder
}

// MockUserControllerInterfaceMockRecorder is the mock recorder for MockUserControllerInterface.
type MockUserControllerInterfaceMockRecorder struct {
	mock *MockUserControllerInterface
}

// NewMockUserControllerInterface creates a new mock instance.
func NewMockUserControllerInterface(ctrl *gomock.Controller) *MockUserControllerInterface {
	mock := &MockUserControllerInterface{ctrl: ctrl}
	mock.recorder = &MockUserControllerInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserControllerInterface) EXPECT() *MockUserControllerInterfaceMockRecorder {
	return m.recorder
}

// SignUpController mocks base method.
func (m *MockUserControllerInterface) SignUpController(request model.SignUpRequest) model.SignUpResponse {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SignUpController", request)
	ret0, _ := ret[0].(model.SignUpResponse)
	return ret0
}

// SignUpController indicates an expected call of SignUpController.
func (mr *MockUserControllerInterfaceMockRecorder) SignUpController(request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignUpController", reflect.TypeOf((*MockUserControllerInterface)(nil).SignUpController), request)
}

// MockHabitControllerInterface is a mock of HabitControllerInterface interface.
type MockHabitControllerInterface struct {
	ctrl     *gomock.Controller
	recorder *MockHabitControllerInterfaceMockRecorder
}

// MockHabitControllerInterfaceMockRecorder is the mock recorder for MockHabitControllerInterface.
type MockHabitControllerInterfaceMockRecorder struct {
	mock *MockHabitControllerInterface
}

// NewMockHabitControllerInterface creates a new mock instance.
func NewMockHabitControllerInterface(ctrl *gomock.Controller) *MockHabitControllerInterface {
	mock := &MockHabitControllerInterface{ctrl: ctrl}
	mock.recorder = &MockHabitControllerInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHabitControllerInterface) EXPECT() *MockHabitControllerInterfaceMockRecorder {
	return m.recorder
}

// AddNewHabitController mocks base method.
func (m *MockHabitControllerInterface) AddNewHabitController(reques model.AddNewHabitRequest) model.AddNewHabitResponse {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddNewHabitController", reques)
	ret0, _ := ret[0].(model.AddNewHabitResponse)
	return ret0
}

// AddNewHabitController indicates an expected call of AddNewHabitController.
func (mr *MockHabitControllerInterfaceMockRecorder) AddNewHabitController(reques interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddNewHabitController", reflect.TypeOf((*MockHabitControllerInterface)(nil).AddNewHabitController), reques)
}
