// Code generated by MockGen. DO NOT EDIT.
// Source: mapper.go

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gin "github.com/gin-gonic/gin"
	gomock "github.com/golang/mock/gomock"
)

// MockGamificationMapper is a mock of GamificationMapper interface.
type MockGamificationMapper struct {
	ctrl     *gomock.Controller
	recorder *MockGamificationMapperMockRecorder
}

// MockGamificationMapperMockRecorder is the mock recorder for MockGamificationMapper.
type MockGamificationMapperMockRecorder struct {
	mock *MockGamificationMapper
}

// NewMockGamificationMapper creates a new mock instance.
func NewMockGamificationMapper(ctrl *gomock.Controller) *MockGamificationMapper {
	mock := &MockGamificationMapper{ctrl: ctrl}
	mock.recorder = &MockGamificationMapperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGamificationMapper) EXPECT() *MockGamificationMapperMockRecorder {
	return m.recorder
}

// GenericRequestJsonMapper mocks base method.
func (m *MockGamificationMapper) GenericRequestJsonMapper(request interface{}, context *gin.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenericRequestJsonMapper", request, context)
	ret0, _ := ret[0].(error)
	return ret0
}

// GenericRequestJsonMapper indicates an expected call of GenericRequestJsonMapper.
func (mr *MockGamificationMapperMockRecorder) GenericRequestJsonMapper(request, context interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenericRequestJsonMapper", reflect.TypeOf((*MockGamificationMapper)(nil).GenericRequestJsonMapper), request, context)
}
